# Site settings
name: yongwx.github.io
email: yongwenxiu23@163.com
author: yongwx
url: 
resume_site: 
github: https://yongwx.github.io/
baseurl: ""
description: 别不好意思拒绝别人，反正那些好意思为难你的人都不是什么好人。
meta_description: 雍文秀;个人博客;
motto: 不管昨天，今天，明天，能豁然开朗就是美好的一天。
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: yongwx
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : 
    disqus :
        short_name : 
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light