#version
version: "1.0"

permalink: /:year/:month/:day/:title/

# 站点设置
title: "yongwx"
email: pyongwenxiu23@163.com
description: "雍文秀的个人博客"
keywords: "yongwx"

# 用户信息设置
weibo_username: yongwx
github_username: yongwx

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil



# 地址设置
baseurl: ""
url: "https://yongwx.github.io/"


# 分页设置
paginate: 2
paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

# duoshuo设置
# duoshuo_shortname: 

# 百度统计设置
# baidu_analysis:
